services:
  neo4j:
    image: neo4j:2026-community
    container_name: hdgrafcehennemi-neo4j
    restart: unless-stopped

    ports:
      - "7474:7474"
      - "7687:7687"

    environment:
      NEO4J_AUTH: neo4j/hdgraf-local-password

    volumes:
      - ./neo4j_data:/data
      - ./neo4j_logs:/logs
      - ./neo4j_import:/import
      - ./neo4j_plugins:/plugins

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10